### ISSUE TITLE
Tapping too many times

### ISSUE THREAD

**Issue by iFac3** [runely/remootio-homey#13]
Hi, thanks for the Homey app!

We have a site where three Renootio 3 are installed. If I tap five times to a gate in Homey, that gate is becomes unreachable for approx 6 minutes. Then reconnects. Have you experiences this behavior?

**Comment by runely** [comment]
I've never tried that. I'll have a go at it tomorrow

**Comment by runely** [comment]
When i tap 5-6 times (very fast) on the garagedoor icon to open/close, the Remootio device is activated 3 times (1. opening, 2. closing, 3. opening) and then it becomes unreacable in the Homey app. For me it reconnected after just a minute (the normal reconnect time).

It seems like the Remootio device or the WebSocket API in the Remootio device is rebooting after too many requests at once.
I get a `The websocket client is not connected` in the log and after a minute it reconnects with a `SERVER HELLO` **frame**.

Out of curiosity, why is this a problem?

I'll do some more tests before i'll contact Remootio about this

**Comment by iFac3** [comment]
Thanks for dealing with my issue. 

If it’s a fail-safe feature and not a bug, then no any issue with it. Is it?
