### ISSUE TITLE
Remootio

### ISSUE THREAD

**Issue by larswestbye** [runely/remootio-homey#27]
Hei. Prøver å skrive på norsk. Jeg bruker Remootio på en port jeg har med to fløyer. Porten har to innstillinger. Helt åpen og luftestilling hvor den ene fløyen går til halvveis åpen. Dette har jeg løst på Remootio ved å bruke begge outputene. Output1 åpner porten helt og output2 setter den ene fløyen halvveis åpen. I Remootio appen blir knappen delt i to. En til hver funksjon. Men når jeg kobler Remootio til Homey med appen din så kommer det bare en knapp og da får jeg problemer med å styre porten som jeg ønsker. Er dette noe du kan fikse?
Lars

**Comment by runely** [comment]
Hei. I neste versjon (**1.4.0**) legger jeg til to nye drivere hvor man kan styre begge outputene. Dokumentasjon kommer på [README](https://github.com/runely/remootio-homey/blob/main/README.md) når versjonen er ferdigstilt, testet og released.

Godt innspill 👍

**Comment by larswestbye** [comment]
Supert! Tusen takk👍



ons. 16. nov. 2022 kl. 22:54 skrev Rune Moskvil Lyngås <
***@***.***>:

**Comment by runely** [comment]
Versjon **1.4.0** er sendt til review og ligger pt tilgjengelig som en [testversjon](https://homey.app/no-no/app/no.runely.remootio/Remootio/test/). Installer gjerne denne og gi meg en tilbakemelding.

For å kunne styre både `gate impulse control` og `free relay output` må du legge til devicen på nytt med en annen driver.

Sjekk ut hvilken driver du må bruke [her](https://github.com/runely/remootio-homey#which-driver-to-use)

**Comment by larswestbye** [comment]
Hei
Da har jeg testet. Den eneste jeg fikk til å virke var output1: free relay
output, output2: gate impuls control. Av disse var det bare output2: gate
impuls control som virket. Men den åpnet porten helt på første trykk, på
andre trykk lukket den ene fløyen helt, mens den andre ble stående i
luftestilling, og på tredje trykk lukket den helt.
Det jeg ønsker er at den ene output åpner og stenger porten helt, mens den
andre outputen åpner den ene fløyen litt på første trykk og stenger den
helt på andre trykk.
Håper det er forståelig det jeg skriver. Legger ved et bilde av hvordan min
Remootio er satt på output configurarion.



tor. 17. nov. 2022 kl. 20:14 skrev Rune Moskvil Lyngås <
***@***.***>:

**Comment by runely** [comment]
Bilder kommer ikke med til GitHub via mail, bilder må du legge inn via en kommentar på GitHub.

I API'et har jeg bare mulighet til å sende en trigger action for å trigge open/close på output 1 eller 2.

For `gate impulse control` så er det bare open/close som fungerer (og knappen endrer status også utifra **status sensoren** tilkoblet på enten input 1 eller input 2.

For `free relay output` så er det bare en trigger jeg kan kjøre. Den får ikke tilbake noe status fra Remootio devicen. **status sensoren** følger bare `gate impulse control`.

Hvilken **output configuration** har du satt opp remootio devicen din mot? Har du endret på **open impulse setting** for open eller close? Isåfall til hva?

Hadde vært kjekt med noen bilder 👍

**Comment by larswestbye** [comment]
![24156711-AAEB-40B7-B52C-D81378B4EA16](https://user-images.githubusercontent.com/118257230/202794254-a0e4877d-a3ae-4cf1-aa7c-ab27d4ca14ef.jpeg)
![36800EBF-8EE3-4730-B747-0EA4C95D1C00](https://user-images.githubusercontent.com/118257230/202794274-6c058065-f05b-4c02-9e86-820a8f950202.jpeg)
![7A371CCF-3981-4190-ADD1-AB6E02A8A603](https://user-images.githubusercontent.com/118257230/202794281-577af556-0374-4c53-8c93-afec30a6384b.png)
![07EC1005-032A-4789-8533-E34D1BE91754](https://user-images.githubusercontent.com/118257230/202794284-a7d7153d-260a-4259-ad12-0a30ec310ad2.jpeg)
![D0FAE562-C7EB-43F9-99ED-22E088B98BE7](https://user-images.githubusercontent.com/118257230/202794288-dcc6dfc8-87e1-421d-9345-67c4ca146968.png)
![68A62965-9F21-48A6-A01A-834480DC2B7C](https://user-images.githubusercontent.com/118257230/202794290-d76368d0-f1e6-4522-a1e4-b802e09f3eb8.jpeg)
![9B34F73F-C198-443A-B871-2E99F962DF2F](https://user-images.githubusercontent.com/118257230/202794292-ad0083fe-1479-44ae-942b-aa9ac7474de5.png)
Prøvde å legge ved det bilde jeg sendte på mail. Ser du det nå?

**Comment by larswestbye** [comment]
Det var definitivt meningen å sende bare ett bilde ja😳Vet ikke hvordan jeg
fikk til det for jeg valgte bare ett. Beklager det. Så du mener at den
output configuartionen jeg har valgt ikke vil fungerer i Homey? Da får jeg
prøve noen av de andre etterhvert. Er ikke så veldig god på dette så det
blir litt prøving og feiling.

fre. 18. nov. 2022 kl. 22:59 skrev Rune Moskvil Lyngås <
***@***.***>:

**Comment by runely** [comment]
Stemmer. `Output 1: output to open Output 2: output to close` og `Output 1: output to close Output 2: output to open` fungerer dårlig eller ikke i det hele tatt sammen med `status sensoren`.

Testet begge konfigurasjonene med test devicen min.

Så de to konfigurasjonene er ikke støttet i Homey appen dessverre

**Comment by larswestbye** [comment]
Ok. Skal prøve å bytte etterhvert. Når jeg får tid. Skal gi deg
tilbakemelding. Takk så langt.

lør. 19. nov. 2022 kl. 08:36 skrev Rune Moskvil Lyngås <
***@***.***>:

**Comment by larswestbye** [comment]
Hei igjen.
Nå ser det ut som det fungerer sånn som jeg ønsker. Har satt output1: free
relay output output2: gate impuls control. Men appen er ikke tilgjengelig i
flows. Er det Fordi den bare er en test?

lør. 19. nov. 2022 kl. 09:09 skrev Lars Westbye ***@***.***>:

**Comment by runely** [comment]
Hmm.. Ser ut til at devicen ikke kommer frem i flows med de nye driverne nei.. Jeg sjekker

**Comment by runely** [comment]
Grunnet at det er brukt sub-capabilities i driverne for å få til to garasjekontrollere på samme driver så fungerer ikke de innebygde flowene, og man må derfor lage sine egne flower. Dette kommer med i versjon **1.4.1**.

**Siden jeg har måttet endre på driveren så må du fjerne og legge til devicen på nytt når ny versjon er lagt inn.**

Veldig bra at du fant ut dette før versjonen gikk public! 👍

**Comment by runely** [comment]
**1.4.1** er sendt til review og ligger klar for testing [her](https://homey.app/a/no.runely.remootio/test/).
Gjerne installer den og gi meg en tilbakemelding :)

**Comment by larswestbye** [comment]
Jeg har reist til Tyskland og er ikke hjemme igjen før torsdag. Skal gi
tilbakemelding når jeg har testet.

søn. 20. nov. 2022 kl. 12:26 skrev Rune Moskvil Lyngås <
***@***.***>:

**Comment by runely** [comment]
`1.4.3` har ligget ute i nesten 2 uker. Regner med at dette er løst nå
