### ISSUE TITLE
External control outside LAN

### ISSUE THREAD

**Issue by felixoslo** [runely/remootio-homey#42]
My Remootio is in another LAN without any possibilities to create VPN connection. Remootio supports "web hook" commands in the API. This means that Remootio can receive a web link and control the gate through the external lan. It would be absolutely fantastic if this can be implemented in the app!!

**Comment by runely** [comment]
Your Homey `must` be able to reach the Remootio device by the local IP-address, somehow!
This Homey app uses the Remootio Websocket API which only talks on the same LAN.

If you want/need to have your Remootio device on another LAN than your Homey is, then you can't use this app.
