### ISSUE TITLE
gate doesn't open with homey

### ISSUE THREAD

**Issue by flori27** [runely/remootio-homey#48]
Hi,

an electrician installed my Remootio 3. I've set up the Remootio app. The gate can be controlled with Bluetooth and WiFi without problems. I've added my remootio device in Homey, manually added it with adding the IP, name, serial number, 2 API keys. 
When clicking on it in homey, nothing happens. 
All the keys, serial number,... where copied and pasted, so no mismatch of characters.
What can I do to make it work?

**Comment by flori27** [comment]
btw, the configuration is not shown when clicking on the gear icon, only other info like api info, ip, remootio version, serial nr, ...

**Comment by runely** [comment]
> What do you mean by "which driver"? The only thing I can choose, is the output configuration. I've chosen the second one, output 1 : free relay

By which driver I mean which Remootio device you chose when you added the Remootio device in Homey.

The second one is actually `Output 1: Free relay output, Output 2: gate impulse control`.
If you chose this the Remootio device has to be setup with the same Output configuration in the Remootio app.
And to operate the gate from the homey app you have to choose `Output 2: gate impulse control` from the drop down on the device in the homey app.

**Comment by flori27** [comment]
About the configuration. I was consulting from the webbrowser. In the smartphone app, the output configuration is shown, in the webbrowser version, it isn't.
I removed the device from Homey, added it again with configuration "gate impulse congtrol", but it didn't help (at first). Then I tried with "advanced settings" -> "is sensor logic flipped" setting to "on", and it worked but the status was showing  the opposite. Then I've set  "is sensor logic flipped" setting to "off" again and It still worked. 
Strange, but I'm glad It's working now.
Thank you very much for your support.

**Comment by runely** [comment]
Out of curiosity, you say you consulted from the webbrowser. But as far as i know Remootio has no user interface in the browser, other than the device access token view. Where did you check?

I'm glad its working as intended for you

**Comment by flori27** [comment]
Hi,

I meant the webbrowser version of Homey.

**Comment by runely** [comment]
Ah, yeah. The homey web version does not show advanced settings on devices
